### PR TITLE
fix: #86 sample 04 terminating on startup

### LINKED ISSUE #86: Transfer Sample 04 terminating immediately after startup
# Bug Report

## Describe the Bug
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. 

### Expected Behavior
All containers should stay up and running. 

### Observed Behavior
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. The other containers are then terminating as well (like they should in such as case, since we are using the "--abort-on-container-exit" parameter). 

## Steps to Reproduce
1. Clone the Samples Project from Github.
2. Configure, build and run Sample No. 1 as described in the README. (Everything is working just fine here)
3. Download opentelemetry agent. Copy this file to the Sample04 root folder. (As instructed by the README)
4. Build Sample04 (of course using the given Gradle Wrapper)
5. Run docker-compose as specified in the README. 

## Context Information

Xubuntu 22.04  
Docker version 24.0.4, build 3713ee1
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

## Detailed Description
I have attached the logging output here:  
[log.txt](https://github.com/eclipse-edc/Samples/files/12011317/log.txt)

## Possible Implementation
None that I know of.

### LINKED ISSUE #127: Sample 04 (OpenTelementry) docker container fails
# Bug Report

## Describe the Bug

transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 INFO : Initialized FS Configuration 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 INFO : Initialized FS Configuration 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 WARNING : The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION. 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 WARNING : The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION. 
transfer-04-open-telemetry-provider-1  | 2023-09-28 08:22:59 SEVERE : Error booting runtime: The following injected fields were not provided: Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension 
transfer-04-open-telemetry-consumer-1  | 2023-09-28 08:22:59 SEVERE : Error booting runtime: The following injected fields were not provided: Field "dataPlaneInstanceStore" of type [interface org.eclipse.edc.connector.dataplane.selector.spi.store.DataPlaneInstanceStore] required by org.eclipse.edc.connector.catalog.CatalogDefaultServicesExtension 
transfer-04-open-telemetry-provider-1 exited with code 255
Aborting on container exit...

### Expected Behavior

Container starts

## Steps to Reproduce

Run the sample: 
1. ./gradlew transfer:transfer-04-open-telemetry:open-telemetry-consumer:build transfer:transfer-04-open-telemetry:open-telemetry-provider:build
2. docker-compose -f transfer/transfer-04-open-telemetry/docker-compose.yaml up --abort-on-container-exit

## Possible Implementation

Provide configuration for: 

- transferProcessApiClient
- dataPlaneInstanceStore

### PR DESCRIPTION
**Pull request by hamidonos**
## What this PR changes/adds

fixes https://github.com/eclipse-edc/Samples/issues/86; commands from README now work.

## Why it does that

basically looked at transfer sample 01 and applied all dependencies/variables from there

## Linked Issue(s)

Closes #127
Closes #86

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
+/*
```
Comment (jimmarino) [inline system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: I see a few of issues with this test:

1. Code should not download remote files like this. Gradle should handle all dependencies
2. The Open Telemetry agent is not needed unless it is explicitly being tested, which it should not be in a sample
3. Overall, I don't understand the purpose of this test. What is it testing?

File: gradle/libs.versions.toml [hunk 2]
```diff
@@ -61,6 +62,8 @@ junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", vers
 junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
 opentelemetry-annotations = { module = "io.opentelemetry:opentelemetry-extension-annotations", version.ref = "openTelemetry" }
 restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }
+testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
```
Comment (jimmarino) [inline gradle/libs.versions.toml:65]: Why do we need TestContainers in the sample?

File: transfer/transfer-04-open-telemetry/docker-compose.yaml [hunk 3]
```diff
@@ -56,7 +60,7 @@ services:
 
   prometheus:
     image: prom/prometheus:v2.30.3
-    container_name: prometheus
+    # container_name: prometheus # does not work with testcontainers
```
Comment (jimmarino) [inline transfer/transfer-04-open-telemetry/docker-compose.yaml:63]: Why is this commented out?

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+ *  Copyright (c) 2023 imec
+ *
+ *  This program and the accompanying materials are made available under the
+ *  terms of the Apache License, Version 2.0 which is available at
+ *  https://www.apache.org/licenses/LICENSE-2.0
+ *
+ *  SPDX-License-Identifier: Apache-2.0
+ *
+ *  Contributors:
+ *       imec
```
Comment (jimmarino) [inline system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:11]: Please use the full company legal name

**Review by jimmarino — CHANGES_REQUESTED** [review]

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java (hunk 1 above)
Comment (hamidonos) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: Hi Jim, I picked up on this PR 
The only thing i added was the file download of the opentelemetry jar. I can move this to the Gradle script ofc.
I assumed the PR was close to be ready-to-merge as in the original PR it was mentioned that the failing tests is the only thing missing. We could ofc rethink the whole solution.

I think we could test the basic workflow like with the previous samples and test if telemetry logs are written or if Jaeger is reachable.

Comment (ndr-brt) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: I agree that the agent should be downloaded by gradle. The test is needed because we decided to add E2E tests on all the samples to avoid regressions on edc upgrades (testing samples manually is a tedious work). This test was provided time ago, I think it still makes sense.

Comment (jimmarino) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: OK, but two points:

1. Is it testing that the agent receives messages? 
2. Open telemetry should be tested in the main repository, tests here should focus on the bootstrap of the samples. In other words, we should be confident open telemetry works with EDC based on the main repo test coverage, and here we only test the functionality added by the sample.

Comment (ndr-brt) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: The idea was to have the tests follow the sample steps from start to end. This should not test the interaction with open telemetry but that what's written in the README file is still working

File: gradle/libs.versions.toml (hunk 2 above)
Comment (hamidonos) [reply gradle/libs.versions.toml:65]: Sample 04 is running in docker compose. We're simulating that in the test case. For that we need testcontainers.

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java (hunk 1 above)
Comment (jimmarino) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: OK so then we can eliminate the open telemetry agent download entirely since it is not under test. The test should just verify the end-to-end flow.

Comment (hamidonos) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: The agent is part of the docker compose file which we use to initialize the testcontainer
We'd have to exclude the agent from the docker compose file for the test case but I wouldn't do so as:

- We'll have two different docker compose files
- We're not testing the original sample setup anymore

I don't think it hurts to just leave the agent download there

Comment (jimmarino) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: OK sounds good, but then we should be testing the same configuration/image that is used in the sample. That would mean not downloading the agent in the test and using the runtime setup from the Gradle project build.

Comment (hamidonos) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: That's what we do now
If you check the gradle builds files you'll see that the agent download is a part of the gradle build step

Comment (jimmarino) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java:1]: Can you please use Gradle's dependency resolution mechanism a pull the dependency from the local cache when building?

https://mvnrepository.com/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent

This will allow us to track dependencies, use Gradle settings for downloads, and enable caching.

**Review by jimmarino — APPROVED** [review]
Looks good

**Review by ndr-brt — APPROVED** [review]
