### PR TITLE
fix: streaming-02-kafka-to-http:fix issues with contract negotiation …

### LINKED ISSUE #339: Multiple errors in sample transfer/streaming/streaming-02-kafka-to-http
# Bug Report

## Describe the Bug

Sample
 transfer/streaming/streaming-02-kafka-to-http

Action

Start negotiate contract
`curl -H 'Content-Type: application/json' -d @transfer/streaming/streaming-02-kafka-to-http/5-negotiate-contract.json  -X POST "http://localhost:28181/management/v3/contractnegotiations" -s | jq
[
`
Explanation 
when trying to start negotiate contract with 5-negotiate-contract.json the returned json states that the multiple fields are missing or blank.

### Expected Behavior

contract-negotiation-id in json will be returned

### Observed Behavior

```
[
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/@type was expected to be http://www.w3.org/ns/odrl/2/Offer but it was not",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/@type",
    "invalidValue": [
      "https://w3id.org/edc/v0.0.1/ns/Offer"
    ]
  },
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/assigner/@id cannot be null or blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/assigner/@id",
    "invalidValue": null
  },
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/target/@id cannot be null or blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/target/@id",
    "invalidValue": null
  }

```
## Steps to Reproduce

Follow 
(https://github.com/eclipse-edc/Samples/tree/main/transfer/streaming/streaming-02-kafka-to-http)

## Context Information
Used commit: https://github.com/eclipse-edc/Samples/commit/1d55b7c2ef109a7b94a9ae2ea124e79ea6fbeb2f
OS: Ubuntu 24.04

## Detailed Description
Same in https://github.com/eclipse-edc/Samples/tree/main/transfer/streaming/streaming-03-kafka-broker

### PR DESCRIPTION
**Pull request by Juboy**
…and data transfer json requests

## What this PR changes/adds

Issues around running streaming-02-kafka-to-http sample. Issues with contract negotiation and date transfer 

Fixed transfer/streaming/streaming-02-kafka-to-http/5-negotiate-contract.json file by including the odrl context. 
Fixed transfer/streaming/streaming-02-kafka-to-http/6-transfer.json file by including the transfer type 

## Why it does that

The contract negotiation was failing because the contract definition was missing the ODRL context, which is required for policy evaluation. Adding the correct ODRL context ensures that contract negotiation can be processed successfully.  

Similarly, the transfer process was not working correctly because the transfer type was missing. Including the transfer type explicitly defines the expected data exchange format, allowing the transfer to proceed without errors.

## Linked Issue(s)

Closes #339

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java [hunk 1]
```diff
@@ -108,7 +108,7 @@ void streamData() {
 
         var destination = Json.createObjectBuilder()
                 .add("type", "HttpData")
-                .add("baseUrl", "http://localhost:" + httpReceiverPort)
+                .add("baseUrl", "http://localhost:4000")
                 .build();
 
         var transferProcessId = CONSUMER.requestAssetFrom("kafka-stream-asset", PROVIDER)
```
Comment (ndr-brt) [inline system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java:114]: To make this test cover the sample, this call should be changed in using the json payload in the resource folders as done in [sample streaming-01](https://github.com/eclipse-edc/Samples/pull/335)

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java [hunk 2]
```diff
@@ -88,12 +90,10 @@ public class Streaming02KafkaToHttpTest {
...
 
-    private final int httpReceiverPort = Ports.getFreePort();
-    private final MockWebServer consumerReceiverServer = new MockWebServer();
 
-    @BeforeEach
-    void setUp() throws IOException {
-        consumerReceiverServer.start(httpReceiverPort);
+    @BeforeAll
+    static void setUp() {
+        httpRequestLoggerContainer.start();
```
Comment (ndr-brt) [inline system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java:96]: this is not needed because the `@Container` annotation has been added to the logger container instance

**Review by ndr-brt — CHANGES_REQUESTED** [review]
Could you open an issue to fix the behavior also in sample streaming-03? I think that's broken as well

**Comment by Juboy** [comment]
Thanks @ndr-brt 
I'll work on the comments

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java (hunk 1 above)
Comment (Juboy) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java]: Fixed. I used all the json payload in the sample this time

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java (hunk 2 above)
Comment (Juboy) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java]: Noted and removed 🚀

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java [hunk 3]
```diff
@@ -108,7 +108,7 @@ void streamData() {
 
         var destination = Json.createObjectBuilder()
                 .add("type", "HttpData")
-                .add("baseUrl", "http://localhost:" + httpReceiverPort)
+                .add("baseUrl", "http://localhost:4000")
```
[the remark this answers is not in the document]
Comment (Juboy) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java]: Here @ndr-brt 

https://github.com/eclipse-edc/Samples/issues/359

File: .github/actions/run-tests/action.yml [hunk 4]
```diff
@@ -12,7 +12,7 @@ runs:
       run: ${{ inputs.command }}
 
     - name: Upload Test Results
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
```
Comment (ndr-brt) [inline .github/actions/run-tests/action.yml:15]: in fact this action and the relative "publish test results" job in the `verify` have been removed so long ago from all the other repos, they can be removed from here as well. Different issue tho :)

**Review by ndr-brt — APPROVED** [review]
LGTM
