### PR TITLE
fix: add missing json fields for sample streaming http-to-http 

### LINKED ISSUE #244: streaming samples
# Bug Report

## Describe the Bug

Working through the samples like described in the ReadMe doenst work cause the negotiate-contract.json is faulty.
This is the error occuring
```json
[
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/@type was expected to be http://www.w3.org/ns/odrl/2/Offer but it was not",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/@type",
    "invalidValue": [
      "https://w3id.org/edc/v0.0.1/ns/Offer"
    ]
  },
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/assigner/@id cannot be null or blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/assigner/@id",
    "invalidValue": null
  },
  {
    "message": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/target/@id cannot be null or blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/policy/http://www.w3.org/ns/odrl/2/target/@id",
    "invalidValue": null
  }
]
```

### Expected Behavior

Working through the sample, the negotiate-contract.json should negotiate the contract about the asset

### Solution

The negotiate-contract.json doesnt have the right format. The right format should look like this:
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "@type": "ContractRequest",
  "counterPartyAddress": "http://localhost:18182/protocol",
  "protocol": "dataspace-protocol-http",
  "policy": {
    "@id": "Y29udHJhY3QtZGVmaW5pdGlvbg==:a2Fma2Etc3RyZWFtLWFzc2V0:ZjJmZWMyOWMtYTU4NC00ODdmLTljMWItMWZjNTc5MzNmZmVi",
    "@type": "http://www.w3.org/ns/odrl/2/Offer",
    "odrl:permission": [],
    "odrl:prohibition": [],
    "odrl:obligation": [],
    "odrl:assigner": {
      "@id": "provider"
    },
    "odrl:target": {
      "@id": "kafka-stream-asset"
    }
  }
}
```

### LINKED ISSUE #334: Missing transferType in sample transfer/streaming/streaming-01-http-to-http
# Bug Report

## Describe the Bug

Sample: 
- transfer/streaming/streaming-01-http-to-http

Action:
- Starting the transfer process, using [transfer.json](https://github.com/eclipse-edc/Samples/blob/main/transfer/streaming/streaming-01-http-to-http/transfer.json):
```shell
curl -H 'Content-Type: application/json' -d @transfer/streaming/streaming-01-http-to-http/transfer.json -X POST "http://localhost:28181/management/v3/transferprocesses" -s | jq
```
Explanation:
When trying to start the transfer, the returned JSON states that the `transferType` is missing or blank.
No transfer process is started.

Error:
- 
### Expected Behavior

The transfer-process is started on both the consumer and provider end and an id for the transfer is returned:
```json
{
  "@type": "IdResponse",
  "@id": "<uuid>",
  "createdAt": 1730894147658,
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  }
}
```

### Observed Behavior
Error:
```json
[
  {
    "message": "mandatory value 'https://w3id.org/edc/v0.0.1/ns/transferType' is missing or it is blank",
    "type": "ValidationFailure",
    "path": "https://w3id.org/edc/v0.0.1/ns/transferType",
    "invalidValue": null
  }
]
```

## Steps to Reproduce

- Follow [Streaming-Sample-01]{https://github.com/eclipse-edc/Samples/blob/main/transfer/streaming/streaming-01-http-to-http/README.md} until starting the transfer process (see action above).

## Context Information
- Used commit: da78c98
- OS: Ubuntu 24.04

## Detailed Description

Things I tried to solve it:
- Adding a `transferType`of various kinds:
  - `HttpData-Push`
  - `HttpStreaming`
  - `Http Streaming`
  i.e.:
  ```json
  {
    "@context": {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "@type": "TransferRequest",
    "dataDestination": {
      "type": "HttpData",
      "baseUrl": "http://localhost:4000"
    },
    "protocol": "dataspace-protocol-http",
    "assetId": "stream-asset",
    "contractId": "{{contract-agreement-id}}",
    "connectorId": "provider",
    "counterPartyAddress": "http://localhost:18182/protocol",
    "transferType": "HttpData-PUSH"
  }
  ```
-> For `HttpData-PUSH` returns a proper ID, but on the provider, the following error is shown:
```shell
SEVERE 2024-11-06T12:55:48.969041699 TransferProcess: ID <uid>. Fatal error while Initiate data flow. Error details: DataPlane not found
WARNING 2024-11-06T12:55:48.969065369 DataPlane not found
```
The transfer-process is terminated shortly after.
-> The others claim an invalid `transferType` (expected):
```shell
[
  {
    "message": "Property transferType not valid: Failed to extract flow type from transferType HttpStreaming",
    "type": "InvalidRequest",
    "path": null,
    "invalidValue": null
  }
]
```
- Tried changing the `dataDestination/type`to `HttpStreaming` having the same issues

## Possible Implementation
-

### PR DESCRIPTION
**Pull request by klumbe**
## What this PR changes/adds

Fixes issues #244 and #334 for sample transfer/streaming/streaming-01-http-to-http
- Missing `assigner` field in contract request
- Missing `transferType` in transfer request
- Did not use JSON files in testcase

## Why it does that
Sample can not be executed completely.

## Linked Issue(s)
Closes #244 
Closes #334

### CODE REVIEW

**Review by ndr-brt — COMMENTED** [review]
while are you working on this field, could you change the `Streaming01httpToHttpTest` to use these files instead of building the requests from scratch?
You can get some inspiration from `Transfer02consumerPullTest` (that already does this).

**Comment by klumbe** [comment]
@ndr-brt:
Since I can't find any doc about how to run the test-cases, I can't fix it that easily.
The official doc returns 404 for almost every link in there (i.e. https://eclipse-edc.github.io/testing.md found in https://eclipse-edc.github.io/documentation/for-contributors/#52-testing-best-practices).

I flew over the convention slightly, does the new name match?

**Comment by ndr-brt** [comment]
> @ndr-brt: Since I can't find any doc about how to run the test-cases, I can't fix it that easily. The official doc returns 404 for almost every link in there (i.e. https://eclipse-edc.github.io/testing.md found in https://eclipse-edc.github.io/documentation/for-contributors/#52-testing-best-practices).
> 
> I flew over the convention slightly, does the new name match?

link is broken, but you can find it under [`contributors manual/writing tests`](https://eclipse-edc.github.io/documentation/for-contributors/testing/)

**Comment by klumbe** [comment]
> link is broken, but you can find it under [`contributors manual/writing tests`](https://eclipse-edc.github.io/documentation/for-contributors/testing/)

Almost all links are broken, unfortunately ;-)

For me, it still does not work for half of the test cases, since Testcontainers does not recognize the docker-engine.
Using the official Docker engine (no Desktop) on Ubuntu 24.04. User is in correct group and can contact the daemon.
Path `/var/run/docker.sock` exists and has `rw` access for the group the user is in.
Tried it with setting the `DOCKER_HOST` variable as well. No change.

**Comment by ndr-brt** [comment]
> > link is broken, but you can find it under [`contributors manual/writing tests`](https://eclipse-edc.github.io/documentation/for-contributors/testing/)
> 
> Almost all links are broken, unfortunately ;-)

contributions are the key ;)

> For me, it still does not work for half of the test cases, since Testcontainers does not recognize the docker-engine. Using the official Docker engine (no Desktop) on Ubuntu 24.04. User is in correct group and can contact the daemon. Path `/var/run/docker.sock` exists and has `rw` access for the group the user is in. Tried it with setting the `DOCKER_HOST` variable as well. No change.

I'm also using docker engine on ubuntu without issues, it worked out-of-the-box, there's no need to do changes, as long as `docker` is executable from the command line by a non root user.
what's the error?

**Comment by klumbe** [comment]
> > > link is broken, but you can find it under [`contributors manual/writing tests`](https://eclipse-edc.github.io/documentation/for-contributors/testing/)
> > 
> > 
> > Almost all links are broken, unfortunately ;-)
> 
> contributions are the key ;)
>
> > For me, it still does not work for half of the test cases, since Testcontainers does not recognize the docker-engine. Using the official Docker engine (no Desktop) on Ubuntu 24.04. User is in correct group and can contact the daemon. Path `/var/run/docker.sock` exists and has `rw` access for the group the user is in. Tried it with setting the `DOCKER_HOST` variable as well. No change.
> 
> I'm also using docker engine on ubuntu without issues, it worked out-of-the-box, there's no need to do changes, as long as `docker` is executable from the command line by a non root user. what's the error?

Strange.
Basically, the long exception-message starts with:
```shell
Advanced01openTelemetryTest > runSampleSteps() FAILED
    java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:274)
```

**Comment by klumbe** [comment]
It seems to be one of those funny things where installing OS updates and rebooting fixes it.
Can't explain why, since OS was pretty up-to-date and settings seemed right, but it worked.

**Comment by ndr-brt** [comment]
> @ndr-brt: Took me a long time, but I fixed it. Not sure why ECA does not evaluate anymore, or why it evaluated before, since I am using my anonymized Github email. I filled out the form though.

I think it is becuse your first commit, that has no email reported: https://github.com/eclipse-edc/Samples/pull/335/commits/2f00b9d846db09c744125cbdaa25b99bc9dd31f4

maybe you could squash the three commits into one that has the correct info

**Comment by klumbe** [comment]
@ndr-brt: 
You mean the last one? Indeed this one was missing the author completely.
Shame on me.
Fixed that by a rebase / amend, should be better now.

Haven't seen the checkstyle errors during testing, fixed those as well. 
Warnings were there before, I am not about to fix those as well.
So it should be good if all Github checks pass.

Btw: Is there a way to only run a certain test? It was quite annoying, since though I tried some things from the Gradle docs,
I could only get all tests running by firing:
```shell
.\gradlew test -DrunAllTests="true"
```

**Comment by ndr-brt** [comment]
> @ndr-brt: You mean the last one? Indeed this one was missing the author completely. Shame on me. Fixed that by a rebase / amend, should be better now.
> 
> Haven't seen the checkstyle errors during testing, fixed those as well. Warnings were there before, I am not about to fix those as well. So it should be good if all Github checks pass.
> 
> Btw: Is there a way to only run a certain test? It was quite annoying, since though I tried some things from the Gradle docs, I could only get all tests running by firing:
> 
> ```shell
> .\gradlew test -DrunAllTests="true"
> ```

if you are using Intellij you just need to add the `-DrunAllTests="true"` in the run configuration.
you could also create a configuration template and make it enabled for all the gradle commands (very handy for EDC projects)

**Comment by klumbe** [comment]
> > @ndr-brt: You mean the last one? Indeed this one was missing the author completely. Shame on me. Fixed that by a rebase / amend, should be better now.
> > Haven't seen the checkstyle errors during testing, fixed those as well. Warnings were there before, I am not about to fix those as well. So it should be good if all Github checks pass.
> > Btw: Is there a way to only run a certain test? It was quite annoying, since though I tried some things from the Gradle docs, I could only get all tests running by firing:
> > ```shell
> > .\gradlew test -DrunAllTests="true"
> > ```
> 
> if you are using Intellij you just need to add the `-DrunAllTests="true"` in the run configuration. you could also create a configuration template and make it enabled for all the gradle commands (very handy for EDC projects)

But this would still run all tests, doesn't it?
Since it was pretty basic testing so far, the setup is quite simple (no sophisticated IDE).
May have to change that once I start real development.

Checks look good now, right?

**Comment by ndr-brt** [comment]
> > if you are using Intellij you just need to add the `-DrunAllTests="true"` in the run configuration. you could also create a configuration template and make it enabled for all the gradle commands (very handy for EDC projects)
> 
> But this would still run all tests, doesn't it? Since it was pretty basic testing so far, the setup is quite simple (no sophisticated IDE). May have to change that once I start real development.
> 

no, this will say to junit: "run the test you want without considering the tag attached to it.

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java [hunk 1]
```diff
@@ -97,14 +96,24 @@ void streamData() throws IOException {
...
-                .add("baseUrl", "http://localhost:" + httpReceiverPort)
-                .build();
-        var transferProcessId = CONSUMER.requestAssetFrom("stream-asset", PROVIDER)
-                .withDestination(destination)
-                .withTransferType("HttpData-PUSH")
-                .execute();
+        var catalogDatasetId = CONSUMER.fetchDatasetFromCatalog(getFileContentFromRelativePath(SAMPLE_FOLDER + "/get-dataset.json"));
+        var negotiateContractBody = getFileContentFromRelativePath(SAMPLE_FOLDER + "/negotiate-contract.json")
+                                        .replace("{{offerId}}", catalogDatasetId);
+        //assertThat(catalogDatasetId).isEqualTo("test", catalogDatasetId);
```
Comment (ndr-brt) [inline system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java:102]: commented out line should be removed

**Review by ndr-brt — COMMENTED** [review]
a little thing to fix then we'll be ready to merge

File: system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java (hunk 1 above)
Comment (klumbe) [reply system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java]: Oh, good catch.
Had been too long yesterday, obviously.
That was my way to find out how to fix the issue that jsonPath rejects colons if not escaped.
A bit tricky when it is the first time to use it at all ;-)

I have amended it to the last commit to not have too many.

**Comment by ndr-brt** [comment]
> Ok, might work with IDEA. You don't know a way to run a specific test through CLI?

sure, for this one just execute:
```
./gradlew :system-tests:test --tests "org.eclipse.edc.samples.transfer.streaming.Streaming01httpToHttpTest.streamData" -DrunAllTests=true
```

**Comment by klumbe** [comment]
> > Ok, might work with IDEA. You don't know a way to run a specific test through CLI?
> 
> sure, for this one just execute:
> 
> ```
> ./gradlew :system-tests:test --tests "org.eclipse.edc.samples.transfer.streaming.Streaming01httpToHttpTest.streamData" -DrunAllTests=true
> ```

Haven't tried it yet, but sounds as if it could work. Thank you.
I had tried it basically without the `-DrunAllTests=true`, since I thought it would do the opposite of what I wanted to achieve.
I read about the fact that otherwise system-tests would not be executed at all, but I thought it would be sort of a side-effect of running all existing test-cases.
Might be a case where we first enlarge the scope to then filter out.
Not too familiar with Gradle unfortunately.

**Review by ndr-brt — APPROVED** [review]
anyway, thanks for the contribution, I'm gonna merge this :rocket:

**Comment by klumbe** [comment]
> > Haven't tried it yet, but sounds as if it could work. Thank you. I had tried it basically without the `-DrunAllTests=true`, since I thought it would do the opposite of what I wanted to achieve. I read about the fact that otherwise system-tests would not be executed at all, but I thought it would be sort of a side-effect of running all existing test-cases. Might be a case where we first enlarge the scope to then filter out. Not too familiar with Gradle unfortunately.
> 
> the `-DrunAllTests=true` basically says "run the selected tests despite the junit tag", given the fact that this test has the "EndToEnd" label, that property is a sort of passepartout to not care about the labels and just run the tests.
> 
> For this test, this command does the same exact thing as the one before
> 
> ```
> ./gradlew :system-tests:test --tests "org.eclipse.edc.samples.transfer.streaming.Streaming01httpToHttpTest.streamData" -DincludeTags="EndToEndTest"
> ```

Thank you for the explanation (and preventing me from dying uneducated ;-)).

**Comment by klumbe** [comment]
> anyway, thanks for the contribution, I'm gonna merge this 🚀

Perfect, thanks. You are welcome. Hope it helps somebody.
